### ISSUE TITLE
Role for RHSM already exists

### ISSUE THREAD

**Issue by EmilienM** [linux-system-roles/linux-system-roles.github.io#16]
The website says that the roadmap includes a role for RHSM.
I want to point out that this role exists (I'm one of the main contributors).

https://github.com/openstack/ansible-role-redhat-subscription/

How would you like to proceed? Would you prefer a move or just update the doc somewhere?

**Comment by pcahyna** [comment]
We have been also considering this role: https://github.com/oasis-roles/rhsm , Cc @robled @seandst @greg-hellings . @tabowling any opinion on tthis point on the roadmap?

**Comment by greg-hellings** [comment]
Our role is feature complete as for what we have encountered a need for, at present. A quick look at the openstack role shows that the OASIS one has a simpler interface. I don't know if that reflects a different feature set or just a different way of achieving the same variables data.

If there is a deficiency between the features needed in the OASIS RHSM role, we will be happy to expand it. Coming together with the openstack role would also be nice so that there can be a reduction in effort.

**Comment by richm** [comment]
Any update on this?
